# Generated by Django 3.2.8 on 2021-10-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjapp', '0005_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='disc',
            new_name='dis',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='img',
            new_name='im',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='nam',
        ),
    ]
